# Les mutations des heures de travail côté Pro (le service et le module), jouées contre test-968 : poser, lancer, restaurer (git checkout). ⛔ COMMITER AVANT de lancer.
import subprocess, sys
W = __import__('os').path.dirname(__import__('os').path.dirname(__import__('os').path.abspath(__file__)))      # la racine du dépôt
M = [
  ('H01', 'le Pro hors des heures n\'est plus retenu', 'server-msg/push.js', "    if (charge.retenable === true && horsHeuresPro(moi, charge) && retenirPro(uid, charge)) return {", "    if (false && charge.retenable === true && horsHeuresPro(moi, charge) && retenirPro(uid, charge)) return {"),
  ('H02', 'le Perso est retenu aussi (le côté n\'est plus lu)', 'server-msg/push.js', "    try { return stockage.coteDe(moi.id, charge.tag) === 'pro'; } catch (e) { return false; }", "    try { return true; } catch (e) { return false; }"),
  ('H03', 'le résumé part sans attendre la reprise', 'server-msg/push.js', "      if (moi && moi.prefs && moi.prefs.heures_pro && heuresPro.horsHeures(moi.prefs.heures_pro, moi.tz, horloge())) continue;", "      if (false) continue;"),
  ('H04', 'le résumé compte aussi ce qui a été lu', 'server-msg/push.js', "      try { convs = convs.filter(c => stockage.pushConvNonLue(uid, c)); }", "      try { convs = convs.filter(c => true || stockage.pushConvNonLue(uid, c)); }"),
  ('H05', 'la route écrit un réglage invalide', 'server-msg/routes.js', "        else return refus(res, 400, 'champ_invalide');\n      }\n", "        else p.heures_pro = b.prefs.heures_pro;\n      }\n"),
  ('H06', 'une nuit appartient au jour où elle FINIT', 'server-msg/heures-pro.js', "  return (r.jours.includes(jour) && minute >= r.debut) || (r.jours.includes(veille) && minute < r.fin);", "  return (r.jours.includes(jour) && minute >= r.debut) || (r.jours.includes(jour) && minute < r.fin);"),
  ('H07', 'la fin de la plage est INCLUSE', 'server-msg/heures-pro.js', "  if (r.debut < r.fin) return r.jours.includes(jour) && minute >= r.debut && minute < r.fin;", "  if (r.debut < r.fin) return r.jours.includes(jour) && minute >= r.debut && minute <= r.fin;"),
  ('H08', 'un fuseau inconnu se lit comme Paris (il coupe)', 'server-msg/heures-pro.js', "  try { parts = formateur(tz || FUSEAU_DEFAUT).formatToParts(new Date(t)); } catch (e) { return null; }", "  try { parts = formateur(tz || FUSEAU_DEFAUT).formatToParts(new Date(t)); } catch (e) { parts = formateur(FUSEAU_DEFAUT).formatToParts(new Date(t)); }"),
  ('H09', 'le module ne lit plus le fuseau de la personne', 'server-msg/heures-pro.js', "  try { parts = formateur(tz || FUSEAU_DEFAUT).formatToParts(new Date(t)); }", "  try { parts = formateur(FUSEAU_DEFAUT).formatToParts(new Date(t)); }"),
  ('H10', 'une mention ne se compte plus', 'server-msg/push.js', "    r.set(charge.tag, (r.get(charge.tag) || 0) + (charge.type === 'mention' ? 1 : 0));", "    r.set(charge.tag, (r.get(charge.tag) || 0));"),
  # la relecture du gardien (8 octobre 2026) : le non-lu de la pastille, l'ordre heures puis réunion, la mémoire pleine qui laisse sonner
  ('G01', 'le résumé compte un message du SYSTÈME', 'server-msg/stockage.js', "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);", '    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);'),
  ('G02', 'le résumé compte un message SUPPRIMÉ pour tous', 'server-msg/stockage.js', "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);", "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);"),
  ('G03', 'le résumé compte un message MASQUÉ pour soi', 'server-msg/stockage.js', "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);", "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);"),
  ('G04', "le résumé oublie depuis quand la personne est membre (attendu NEUTRALISÉ : à l'entrée, lu_seq = depuis_seq − 1)", 'server-msg/stockage.js', "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);", "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);"),
  ('G05', 'le résumé compte un message ÉCHU (attendu NEUTRALISÉ : le balayeur purge les échus)', 'server-msg/stockage.js', "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL AND (x.expire_ts IS NULL OR x.expire_ts > ?)\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(horloge(), conv, uid);", "    const r = Q(`SELECT 1 AS x FROM membre m JOIN message x ON x.conv = m.conv AND x.seq > m.lu_seq AND x.seq >= m.depuis_seq AND x.auteur <> m.uid\n                   AND x.type <> 'systeme' AND x.supprime_le IS NULL\n                   AND NOT EXISTS (SELECT 1 FROM msg_masque k WHERE k.conv = x.conv AND k.seq = x.seq AND k.uid = m.uid)\n                 WHERE m.conv = ? AND m.uid = ? AND m.quitte_le IS NULL LIMIT 1`).get(conv, uid);"),
  ('G06', "l'ancien ordre : la réunion avant les heures", 'server-msg/push.js', "    if (charge.retenable === true && horsHeuresPro(moi, charge) && retenirPro(uid, charge)) return { envoyes: 0, appareils: abos.length, raison: 'hors_heures' };\n    if (charge.retenable === true && !(moi.prefs && moi.prefs.pause_reunion === false)) {\n      let dedans = false; try { dedans = enSalle(uid); } catch (e) { dedans = false; }\n      if (dedans && retenir(uid, charge)) return { envoyes: 0, appareils: abos.length, raison: 'retenue' };\n    }\n", "    if (charge.retenable === true && !(moi.prefs && moi.prefs.pause_reunion === false)) {\n      let dedans = false; try { dedans = enSalle(uid); } catch (e) { dedans = false; }\n      if (dedans && retenir(uid, charge)) return { envoyes: 0, appareils: abos.length, raison: 'retenue' };\n    }\n    if (charge.retenable === true && horsHeuresPro(moi, charge) && retenirPro(uid, charge)) return { envoyes: 0, appareils: abos.length, raison: 'hors_heures' };\n"),
  ('G07', "heures, mémoire pleine : la conversation de trop est retenue sans être comptée (l'ancien « perdu »)", 'server-msg/push.js', '    if (!r.has(charge.tag) && r.size >= CONVS_MAX) return false;', '    if (!r.has(charge.tag) && r.size >= CONVS_MAX) return true;'),
  ('G08', "heures, personnes pleines : tout est vidé (l'ancien clear)", 'server-msg/push.js', '    if (!r) { if (retenusPro.size >= PERSONNES_MAX) return false; r = new Map();', '    if (!r) { if (retenusPro.size >= PERSONNES_MAX) retenusPro.clear(); r = new Map();'),
  ('G09', "réunion, personnes pleines : tout est vidé (l'ancien clear)", 'server-msg/push.js', '    if (!r) { if (retenus.size >= PERSONNES_MAX) return false; r = { convs: new Set(), mentions: 0 };', '    if (!r) { if (retenus.size >= PERSONNES_MAX) retenus.clear(); r = { convs: new Set(), mentions: 0 };'),
  ('G10', 'réunion, mémoire pleine : la conversation de trop est retenue sans être comptée', 'server-msg/push.js', '    if (conv && !r.convs.has(conv) && r.convs.size >= CONVS_MAX) return false;', '    if (conv && !r.convs.has(conv) && r.convs.size >= CONVS_MAX) return true;'),
  ('G11', 'les plafonds ne lisent plus la configuration (100 et 20 000 en dur)', 'server-msg/push.js', '  const CONVS_MAX = Number.isInteger(pc.retenusConvsMax) ? pc.retenusConvsMax : 100, PERSONNES_MAX = Number.isInteger(pc.retenusPersonnesMax) ? pc.retenusPersonnesMax : 20000;', '  const CONVS_MAX = 100, PERSONNES_MAX = 20000;'),
  ('G12', "la réunion retient même quand sa mémoire refuse (le retour de retenir n'est plus lu)", 'server-msg/push.js', "      if (dedans && retenir(uid, charge)) return { envoyes: 0, appareils: abos.length, raison: 'retenue' };", "      if (dedans) { retenir(uid, charge); return { envoyes: 0, appareils: abos.length, raison: 'retenue' }; }"),
  ('G13', "la configuration n'a plus de borne basse (zéro démarre)", 'server-msg/config.js', 'retenusConvsMax: [1, 1000], retenusPersonnesMax: [1, 1000000],', 'retenusConvsMax: [0, 1000], retenusPersonnesMax: [0, 1000000],'),
]
mord = 0
for (code, nom, f, avant, apres) in M:
    p = W + '/' + f
    s = open(p, encoding='utf-8').read()
    if s.count(avant) != 1:
        print(code, 'CIBLE INTROUVABLE (' + str(s.count(avant)) + ')'); continue
    open(p, 'w', encoding='utf-8').write(s.replace(avant, apres))
    try:
        r = subprocess.run(['node', 'tests/test-968.js'], cwd=W, capture_output=True, text=True, timeout=180)
        sortie = r.stdout + r.stderr
    except subprocess.TimeoutExpired:
        sortie = 'DÉLAI'
    subprocess.run(['git', 'checkout', f], cwd=W, capture_output=True)
    ko = [l.strip() for l in sortie.split('\n') if l.strip().startswith('✗')]
    if ko or 'DÉLAI' in sortie: mord += 1
    print(code, ('MORD : ' + str(len(ko)) + ' ✗ — ' + (ko[0][:150] if ko else 'délai')) if (ko or 'DÉLAI' in sortie) else 'NE MORD PAS', '—', nom)
d = subprocess.run(['git', 'diff', '--stat'], cwd=W, capture_output=True, text=True).stdout.strip()
print('—— bilan :', mord, 'sur', len(M), '— arbre propre' if not d else '— ⚠️ ARBRE SALE : ' + d)
